[package]
name = "cargo-dockerize"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cargo_dockerize"
path = "src/lib.rs"
doc = true

[[bin]]
name = "cargo-dockerize"
path = "src/main.rs"
doc = false

[dependencies]
cargo_toml = "0.9"
cargo_metadata = "0.14.0"
clap = "2"
serde = "1"
serde_json = "1"
tera = "1"
itertools = "0.10"

[package.metadata.docker]
base = "ubuntu:20.04"
deps_hash = "aaa"
env = [
    { name = "TZ", value = "Etc/UTC" },
    { name = "APP_USER", value = "appuser" },
    { name = "APP", value = "/usr/src/app" },
]
copy_dest_dir = "/usr/surc/app"
user = "appuser"
run = ["echo hello", "ls -al"]
expose = [80, 8080]
workdir = "/usr/src/app"
entrypoint = "/usr/src/app/myshell.sh"
