[package]
name = "cargo-dockerize"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cargo_dockerize"
path = "src/lib.rs"
doc = true

[[bin]]
name = "cargo-dockerize"
path = "src/main.rs"
doc = false

[dependencies]
cargo_toml = "0.9"
cargo_metadata = "0.14.0"
clap = "2"
serde = "1"
serde_json = "1"
tera = "1"
itertools = "0.10"
sha2 = "0.9"
futures = { version = "0.3.*" }
tokio = { version = "1", features = ["full"] }
aws_sdk_ecr = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.16-alpha", package = "aws-sdk-ecr" }
base64 = {version = "0.13.0"}

[package.metadata.docker]
base = "ubuntu:20.04"
deps_hash = "f99c5fa81d58ae8c0cfb03fc233ef8eddda71b84628b96880df1e51e15f71a56"
env = [
    { name = "TZ", value = "Etc/UTC" },
    { name = "APP_USER", value = "appuser" },
    { name = "APP", value = "/usr/src/app" },
]
copy_dest_dir = "/usr/src/app/"
extra_copies = [
    { source = "test-file", destination = "/usr/src/app/" }
]