[package]
name = "simple"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"

[package.metadata.build-dist.docker]
base = "ubuntu:20.04"

deps_hash = "f9d194bf3f00f0b1bbd71a6c4d4853c67229a115460aea78cc7f0dcbb80abcd2"

env = [
    { name = "TZ", value = "Etc/UTC" },
    { name = "APP_USER", value = "appuser" },
    { name = "APP", value = "/usr/src/app" },
]
copy_dest_dir = "/usr/src/app/"

extra_copies = [
    { source = "src/test/test-file", destination = "/usr/src/app/" },
]

extra_commands = [
    "RUN ls -al",
    "RUN echo hello > hello.txt",
    "RUN cat /usr/src/app/test-file",
]

expose = [80, 100]

workdir = "/usr/src/app/"
