name: verify
on: [push]

jobs:
  cowsay:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v2
      - run: echo hello
      
  lint:
    name: Running Linter
    runs-on: [self-hosted, ubuntu]
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    
    - name: run formatting check
      run: make check-format

    - name: Run build checks
      run: make check-build

    - name: Run clippy checks
      run: make check-clippy

    - name: Run dockerize checks
      run: make check-dockerize
  
  test:
    name: Running Test
    needs: lint
    runs-on: [self-hosted, ubuntu]
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Build tests
      run:  make test-build

  build_release:
    name: Building release binaries
    needs: lint
    runs-on: [self-hosted, ubuntu]
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build release
      run:  make build-release

  dockerize:
    name: Building docker image and deploying them
    runs-on: [self-hosted, ubuntu]
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2

    - name: Docker build
      run: make dockerize-release

    - name: Docker push image
      run: make dockerize-push
