name: verify
on: [push]

jobs:
  check:
    name: Check version of cargo
    strategy: 
      matrix:
        include:
          - os: [self-hosted, windows, base, build]
          - os: [self-hosted, linux, base, build]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Check cargo version
        run: cargo --version
        
      - name: Cargo build 
        run: cargo build