name: verify
on: [push]

jobs:
  cowsay:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v2
      - run: echo hello
      
  lint:
    name: Running Linter
    runs-on: [self-hosted, ubuntu]
    container:
      image: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    
    - name: run formatting check
      run: make check-format

  test:
    name: Running tests
    needs: lint
    strategy:
      matrix:
        include:
          - os: [self-hosted, windows]
            container: ghcr.io/legion-labs/build-env-win-rust:0.1.0
            workdir: C:\github\workspace
          - os: [self-hosted, ubuntu]
            container: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
            workdir: /github/workspace
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build tests
        run: >-
          docker run
          --name cargo_build
          --rm
          --workdir ${{ matrix.workdir }}
          -v ${{ github.workspace }}:${{ matrix.workdir }}
          ${{ matrix.container }}
          echo Hello-you
