name: verify
on: [push]

jobs:
  test-windows:
    runs-on: [self-hosted, windows]
    steps:
      - uses: actions/checkout@v2
      - run: docker version
  test-win-build-rust:
    runs-on: [self-hosted, winrust]
    steps:
      - uses: actions/checkout@v2
      - run: docker version

  # test:
  #   name: Running tests
  #   strategy:
  #     matrix:
  #       include:
  #         - os: [self-hosted, win-build-rust]
  #           container: ghcr.io/legion-labs/build-env-win-rust:0.1.0
  #           workdir: C:\github\workspace
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Check machine


      # - name: Build tests
      #   run: >-
      #     docker run
      #     --name cargo_build
      #     --rm
      #     --workdir ${{ matrix.workdir }}
      #     -v ${{ github.workspace }}:${{ matrix.workdir }}
      #     ${{ matrix.container }}
      #     echo Hello-you
