name: verify
on: [push]

jobs:
  cowsay:
    runs-on: self-hosted,m6.xlarge
    container: npalm/cowsay

    steps:
      - uses: actions/checkout@v2
      - run: cowsay -f ghostbusters " Who ya gonna call?"
