name: verify
on: [push]

jobs:
  cargo-build-on-vm:
    name: Run cargo version and cargo build on VM
    strategy: 
      matrix:
        include:
          - os: [self-hosted, windows, base, build]
          - os: [self-hosted, linux, base, build]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Check cargo version
        run: cargo --version
        
      - name: Cargo build 
        run: cargo build
  cargo-build-on-container:
    name: Run cargo version and cargo build on Container
    strategy:
      matrix:
        include:
          - os: [self-hosted, windows, c5.4xlarge]
            container: ghcr.io/legion-labs/build-env-win-rust:0.1.0
            workdir: C:\github\workspace
          - os: [self-hosted, ubuntu]
            container: ghcr.io/legion-labs/build-env-linux-rust:0.1.0
            workdir: /github/workspace
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cargo Version 
        run: cargo version

      - name: Cargo Build
        run: cargo build