name: verify
on: [push]

jobs:
  cowsay:
    runs-on: [self-hosted, ubuntu]
    container: npalm/cowsay
    steps:
      - uses: actions/checkout@v2
      - run: cowsay -f ghostbusters "Testing Who ya gonna call?"
      
  lint:
    runs-on: [self-hosted, ubuntu]
    steps:
      - uses: actions/checkout@v2

      - name: Run hello
        run: echo "Hello world"